### PR TITLE
Update to latest Wit API

### PR DESCRIPTION
**Pull request by micahwedemeyer**
*Note*!!! This is not ready for merge yet. I'm just opening this PR to notify you that I'm working on this. I'll keep pushing updates to it as I go along.

Specifically, here are the big things:

- Update to Elixir 1.4 and fix deprecation warnings
- Update to Wit API 20160526, which is the latest, as best as I can tell

Please drop a note to say whether you plan to eventually accept this PR or if there's anything you disagree with.

### CODE REVIEW

**Comment by zabirauf** [comment]
Thanks for sending the pull request. Let me know when the changes are ready, I'll take a look and merge.

**Comment by micahwedemeyer** [comment]
I think it's ready for review and merge now. I'm not really sure how to get the Travis CI tests to pass, as the tests rely on an actual Wit chat bot. Plus, the CI config needs to be updated for Elixir 1.4. If you'd like, add me to the Travis project and I can play with the settings.

**Comment by micahwedemeyer** [comment]
This will also fix #6

**Comment by zabirauf** [comment]
@micahwedemeyer I couldn't find a setting in Travis to add you so added you to this project as collaborator, see if you can now see this repo in travis. When you are done with changes let me know, I'll do the review and merge to master.

**Pull request merged**
